version: "3"
services:
  etcd:
    image: soyking/etcd-goreman:3.2.7
    environment:
      - CLIENT_ADDR=etcd
    ports:
      - "2379:2379"
    networks:
      - webnet
  web:
    image: gofi:latest
    environment:
      - DATA_PATH=/app/data/
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 80M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - etcd
    networks:
      - webnet
    volumes:
      - app-volume:/app/data
networks:
  webnet:
volumes:
  app-volume: