# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema.proto',
  package='messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cschema.proto\x12\x08messages\")\n\x0bGofiMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\n\n\x08GofiVoid2B\n\x04Gofi\x12:\n\x04Send\x12\x15.messages.GofiMessage\x1a\x15.messages.GofiMessage\"\x00(\x01\x30\x01\x62\x06proto3')
)




_GOFIMESSAGE = _descriptor.Descriptor(
  name='GofiMessage',
  full_name='messages.GofiMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='messages.GofiMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='messages.GofiMessage.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=67,
)


_GOFIVOID = _descriptor.Descriptor(
  name='GofiVoid',
  full_name='messages.GofiVoid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['GofiMessage'] = _GOFIMESSAGE
DESCRIPTOR.message_types_by_name['GofiVoid'] = _GOFIVOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GofiMessage = _reflection.GeneratedProtocolMessageType('GofiMessage', (_message.Message,), dict(
  DESCRIPTOR = _GOFIMESSAGE,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:messages.GofiMessage)
  ))
_sym_db.RegisterMessage(GofiMessage)

GofiVoid = _reflection.GeneratedProtocolMessageType('GofiVoid', (_message.Message,), dict(
  DESCRIPTOR = _GOFIVOID,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:messages.GofiVoid)
  ))
_sym_db.RegisterMessage(GofiVoid)



_GOFI = _descriptor.ServiceDescriptor(
  name='Gofi',
  full_name='messages.Gofi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='messages.Gofi.Send',
    index=0,
    containing_service=None,
    input_type=_GOFIMESSAGE,
    output_type=_GOFIMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOFI)

DESCRIPTOR.services_by_name['Gofi'] = _GOFI

# @@protoc_insertion_point(module_scope)
